/* Generated by            cobc 1.1.0 */
/* Generated from          roda.cbl */
/* Generated at            Nov 29 2016 04:08:24 BRST */
/* OpenCOBOL build date    Feb 07 2016 10:28:13 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C roda.cbl */

/* Frame stack declaration */
struct cob_frame {
	int	perform_through;
	void	*return_address;
};

/* Union for CALL statement */
union cob_call_union {
	void *(*funcptr)();
	int  (*funcint)();
	void *func_void;
};
union cob_call_union	cob_unifunc;


/* Storage */

/* PROGRAM-ID : RODA */
static unsigned char b_1[4] __attribute__((aligned));	/* RETURN-CODE */
static unsigned char b_5[8] __attribute__((aligned));	/* CTE-PROG */
static unsigned char b_6[6] __attribute__((aligned));	/* CTE-VERS */
static unsigned char b_7[17] __attribute__((aligned));	/* MAX-PCLD */
static unsigned char b_8[8] __attribute__((aligned));	/* COMBINA */

/* End of storage */


/* Attributes */

static const cob_field_attr a_1 = {16, 4, 0, 0, NULL};
static const cob_field_attr a_2 = {16, 17, 2, 1, NULL};
static const cob_field_attr a_3 = {18, 17, 2, 1, NULL};
static const cob_field_attr a_4 = {33, 0, 0, 0, NULL};
static const cob_field_attr a_5 = {1, 0, 0, 0, NULL};
static const cob_field_attr a_6 = {16, 8, 0, 0, NULL};
static const cob_field_attr a_7 = {17, 4, 0, 1, NULL};
static const cob_field_attr a_8 = {16, 9, 0, 0, NULL};
static const cob_field_attr a_9 = {17, 9, 0, 1, NULL};

/* Fields */

/* PROGRAM-ID : RODA */
static cob_field f_5	= {8, b_5, &a_4};	/* CTE-PROG */
static cob_field f_7	= {17, b_7, &a_2};	/* MAX-PCLD */
static cob_field f_8	= {8, b_8, &a_4};	/* COMBINA */
static cob_field f_17	= {9, NULL, &a_8};	/* GDA-RETURN-CODE */
static cob_field f_18	= {21, NULL, &a_5};	/* DATA-HORA */
static cob_field f_20	= {8, NULL, &a_6};	/* HORA */
static cob_field f_22	= {2119, NULL, &a_5};	/* BOOK */
static cob_field f_24	= {4, NULL, &a_9};	/* SEQL-ERRO */
static cob_field f_25	= {120, NULL, &a_4};	/* TX-ERRO */
static cob_field f_27	= {9, NULL, &a_3};	/* VL-ENTD */
static cob_field f_28	= {2, NULL, &a_7};	/* QT-GR */

/* End of fields */

/* Constants */
static cob_field c_1	= {4, (unsigned char *)"5000", &a_1};
static cob_field c_2	= {6, (unsigned char *)" Teste", &a_4};
static cob_field c_3	= {11, (unsigned char *)" RET-CODE: ", &a_4};
static cob_field c_4	= {2, (unsigned char *)" (", &a_4};
static cob_field c_5	= {2, (unsigned char *)") ", &a_4};
static cob_field c_6	= {17, (unsigned char *)" 888 - FIM NORMAL", &a_4};

