/* Generated by            cobc 1.1.0 */
/* Generated from          roda.cbl */
/* Generated at            Nov 29 2016 04:08:24 BRST */
/* OpenCOBOL build date    Feb 07 2016 10:28:13 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C roda.cbl */

#define  __USE_STRING_INLINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libcob.h>

#define COB_SOURCE_FILE		"roda.cbl"
#define COB_PACKAGE_VERSION	"1.1"
#define COB_PATCH_LEVEL		0

/* Global variables */
#include "roda.c.h"

static void
cob_decimal_set_int (cob_decimal *d, const int n)
{
	mpz_set_si (d->value, n);
	d->scale = 0;
}

static void
cob_decimal_set_uint (cob_decimal *d, const unsigned int n)
{
	mpz_set_ui (d->value, n);
	d->scale = 0;
}

/* Function prototypes */

int RODA (void);
static int RODA_ (const int);

/* Functions */

int
RODA ()
{
  return RODA_ (0);
}

static int
RODA_ (const int entry)
{
  /* Local variables */
  #include "roda.c.l.h"

  static int initialized = 0;
  static cob_field *cob_user_parameters[COB_MAX_FIELD_PARAMS];
  static struct cob_module module = { NULL, NULL, NULL, NULL, cob_user_parameters, 0, '.', '$', ',', 1, 1, 1, 0 };

  /* Start of function code */

  /* CANCEL callback handling */
  if (unlikely(entry < 0)) {
  	if (!initialized) {
  		return 0;
  	}
  	mpz_clear (d0.value);
  	d0.scale = 0;
  	mpz_clear (d1.value);
  	d1.scale = 0;
  	mpz_clear (d2.value);
  	d2.scale = 0;
  	mpz_clear (d3.value);
  	d3.scale = 0;
  	mpz_clear (d4.value);
  	d4.scale = 0;
  	initialized = 0;
  	return 0;
  }

  /* Initialize frame stack */
  frame_ptr = &frame_stack[0];
  frame_ptr->perform_through = 0;

  /* Push module stack */
  module.next = cob_current_module;
  cob_current_module = &module;

  /* Initialize program */
  if (unlikely(initialized == 0))
    {
      if (!cob_initialized) {
        cob_fatal_error (COB_FERROR_INITIALIZED);
      }
      cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
      if (module.next)
        cob_set_cancel ((const char *)"RODA", (void *)RODA, (void *)RODA_);
      /* Initialize decimal numbers */
      cob_decimal_init (&d0);
      cob_decimal_init (&d1);
      cob_decimal_init (&d2);
      cob_decimal_init (&d3);
      cob_decimal_init (&d4);

      (*(int *) (b_1)) = 0;
      memcpy (b_5, "RODA", 4);
      memset (b_5 + 4, 32, 4);
      memcpy (b_6, "VRS001", 6);
      cob_move (&c_1, &f_7);
      memcpy (b_8, "combina ", 8);
      initialized = 1;
    }

  /* Allocate LOCAL storage */
  b_9 = cob_malloc (12);
  b_16 = cob_malloc (9);
  b_18 = cob_malloc (21);
  b_22 = cob_malloc (2119);
  b_43 = cob_malloc (4);

  /* Initialialize LOCAL storage */
  memset (b_9, 0, 12);
  memset (b_16, 48, 9);
  memset (b_18, 32, 8);
  memset (b_18 + 8, 48, 8);
  memset (b_18 + 16, 32, 5);
  memset (b_22, 0, 4);
  memset (b_22 + 4, 32, 120);
  cob_set_packed_zero ((f_27.data = b_22 + 124, &f_27));
  memset (b_22 + 133, 0, 2);
  for (i1 = 1; i1 <= 10; i1++)
    {
      memset (b_22 + 135 + 164 * (i1 - 1), 0, 4);
      for (i2 = 1; i2 <= 8; i2++)
        {
          memset (b_22 + 139 + 20 * (i2 - 1) + 164 * (i1 - 1), 0, 2);
          cob_set_packed_zero ((f0.size = 9, f0.data = b_22 + 141 + 20 * (i2 - 1) + 164 * (i1 - 1), f0.attr = &a_3, &f0));
          cob_set_packed_zero ((f0.size = 9, f0.data = b_22 + 150 + 20 * (i2 - 1) + 164 * (i1 - 1), f0.attr = &a_3, &f0));
        }
    }
  memset (b_22 + 1775, 0, 344);
  memcpy (b_43, "10", 2);
  *(unsigned char *)(b_43 + 2) = 32;
  *(b_43 + 3) = 56;

  cob_save_call_params = cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Entry RODA */

  l_2:;

  /* 000000-PRINCIPAL SECTION */

  /* MAIN PARAGRAPH */

  /* roda.cbl:57: DISPLAY */
  {
    cob_display (0, 1, 2, &f_5, &c_2);
  }
  /* roda.cbl:58: MOVE */
  {
    cob_move (cob_intr_current_date (0, 0), (f_18.data = b_18, &f_18));
  }
  /* roda.cbl:59: DISPLAY */
  {
    cob_display (0, 1, 1, cob_intr_random (1, (f_20.data = b_18 + 8, &f_20)));
  }
  /* roda.cbl:61: MOVE */
  {
    (*(int *)(b_22)) = 0;
  }
  /* roda.cbl:62: MOVE */
  {
    memset (b_22 + 4, 32, 120);
  }
  /* roda.cbl:63: MOVE */
  {
    cob_set_packed_zero ((f_27.data = b_22 + 124, &f_27));
  }
  /* roda.cbl:66: COMPUTE */
  {
    {
      {
        cob_decimal_set_field (&d0, cob_intr_random (0));
        cob_decimal_set_uint (&d2, cob_get_numdisp (b_43, 2));
        cob_decimal_set_int (&d4, 1);
        cob_decimal_sub (&d2, &d4);
        cob_decimal_set_int (&d3, 1);
        cob_decimal_add (&d2, &d3);
        cob_decimal_mul (&d0, &d2);
        cob_decimal_set_int (&d1, 1);
        cob_decimal_add (&d0, &d1);
        cob_decimal_get_field (&d0, (f_28.data = b_22 + 133, &f_28), 0);
      }
    }
  }
  /* roda.cbl:67: PERFORM */
  {
    (*(short *)(b_9)) = 1;
    while (1)
      {
        if (((int)cob_cmp_s16_binary (b_9, (*(short *)(b_22 + 133))) >  0))
          break;
        {
          /* roda.cbl:69: MOVE */
          {
            memcpy (b_22 + 135 + 164 * ((*(short *)(b_9)) - 1), b_9, 2);
          }
          /* roda.cbl:70: COMPUTE */
          {
            {
              {
                cob_decimal_set_field (&d0, cob_intr_random (0));
                cob_decimal_set_uint (&d2, cob_get_numdisp (b_43 + 3, 1));
                cob_decimal_set_int (&d4, 1);
                cob_decimal_sub (&d2, &d4);
                cob_decimal_set_int (&d3, 1);
                cob_decimal_add (&d2, &d3);
                cob_decimal_mul (&d0, &d2);
                cob_decimal_set_int (&d1, 1);
                cob_decimal_add (&d0, &d1);
                cob_decimal_get_field (&d0, (f0.size = 2, f0.data = b_22 + 137 + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_7, &f0), 0);
              }
            }
          }
          /* roda.cbl:74: MOVE */
          {
            (*(short *)(b_9 + 6)) = 0;
          }
          /* roda.cbl:76: PERFORM */
          {
            (*(short *)(b_9 + 4)) = 1;
            while (1)
              {
                if (((int)cob_cmp_s16_binary (b_9 + 4, (*(short *)(b_22 + 137 + 164 * ((*(short *)(b_9)) - 1)))) >  0))
                  break;
                {
                  /* roda.cbl:78: MOVE */
                  {
                    memcpy (b_22 + 139 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), b_9 + 4, 2);
                  }
                  /* roda.cbl:80: IF */
                  {
                    if (((int)cob_cmp_s16_binary (b_9 + 4, 1) == 0))
                      {
                        /* roda.cbl:81: COMPUTE */
                        {
                          {
                            {
                              cob_decimal_set_field (&d0, cob_intr_random (0));
                              cob_decimal_set_field (&d2, &f_7);
                              cob_decimal_set_int (&d4, 1);
                              cob_decimal_sub (&d2, &d4);
                              cob_decimal_set_int (&d3, 1);
                              cob_decimal_add (&d2, &d3);
                              cob_decimal_mul (&d0, &d2);
                              cob_decimal_set_int (&d1, 1);
                              cob_decimal_add (&d0, &d1);
                              cob_decimal_get_field (&d0, (f0.size = 9, f0.data = b_22 + 150 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0), 2);
                            }
                          }
                        }
                        /* roda.cbl:84: COMPUTE */
                        {
                          {
                            {
                              cob_decimal_set_field (&d0, cob_intr_random (0));
                              cob_decimal_set_field (&d2, (f0.size = 9, f0.data = b_22 + 150 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0));
                              cob_decimal_set_int (&d4, 1);
                              cob_decimal_sub (&d2, &d4);
                              cob_decimal_set_int (&d3, 1);
                              cob_decimal_add (&d2, &d3);
                              cob_decimal_mul (&d0, &d2);
                              cob_decimal_set_int (&d1, 1);
                              cob_decimal_add (&d0, &d1);
                              cob_decimal_get_field (&d0, (f0.size = 9, f0.data = b_22 + 141 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0), 2);
                            }
                          }
                        }
                      }
                    else
                      {
                        /* roda.cbl:88: COMPUTE */
                        {
                          {
                            {
                              cob_decimal_set_field (&d0, cob_intr_random (0));
                              cob_decimal_set_field (&d2, &f_7);
                              cob_decimal_set_field (&d4, (f0.size = 9, f0.data = b_22 + 150 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0));
                              cob_decimal_sub (&d2, &d4);
                              cob_decimal_set_int (&d3, 1);
                              cob_decimal_add (&d2, &d3);
                              cob_decimal_mul (&d0, &d2);
                              cob_decimal_set_field (&d1, (f0.size = 9, f0.data = b_22 + 150 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0));
                              cob_decimal_add (&d0, &d1);
                              cob_decimal_get_field (&d0, (f0.size = 9, f0.data = b_22 + 150 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0), 2);
                            }
                          }
                        }
                        /* roda.cbl:93: COMPUTE */
                        {
                          {
                            {
                              cob_decimal_set_field (&d0, cob_intr_random (0));
                              cob_decimal_set_field (&d2, (f0.size = 9, f0.data = b_22 + 150 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0));
                              cob_decimal_set_field (&d4, (f0.size = 9, f0.data = b_22 + 141 + 20 * ((*(short *)(b_9 + 6)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0));
                              cob_decimal_sub (&d2, &d4);
                              cob_decimal_set_int (&d3, 1);
                              cob_decimal_add (&d2, &d3);
                              cob_decimal_mul (&d0, &d2);
                              cob_decimal_set_field (&d1, (f0.size = 9, f0.data = b_22 + 141 + 20 * ((*(short *)(b_9 + 6)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0));
                              cob_decimal_add (&d0, &d1);
                              cob_decimal_get_field (&d0, (f0.size = 9, f0.data = b_22 + 141 + 20 * ((*(short *)(b_9 + 4)) - 1) + 164 * ((*(short *)(b_9)) - 1), f0.attr = &a_3, &f0), 2);
                            }
                          }
                        }
                      }
                  }
                  /* roda.cbl:100: MOVE */
                  {
                    memcpy (b_9 + 6, b_9 + 4, 2);
                  }
                }
                (*(short *)(b_9 + 4)) = ((*(short *)(b_9 + 4)) + 1);
              }
          }
        }
        (*(short *)(b_9)) = ((*(short *)(b_9)) + 1);
      }
  }
  /* roda.cbl:105: CALL */
  {
    {

      module.cob_procedure_parameters[0] = (f_22.data = b_22, &f_22);
      module.cob_procedure_parameters[1] = NULL;
      module.cob_procedure_parameters[2] = NULL;
      module.cob_procedure_parameters[3] = NULL;
      module.cob_procedure_parameters[4] = NULL;
      cob_call_params = 1;
      cob_unifunc.func_void = cob_call_resolve_1 (&f_8);
      (*(int *) (b_1)) = cob_unifunc.funcint (b_22);
    }
  }
  /* roda.cbl:107: IF */
  {
    if (((int)((*(int *) (b_1)) - 0) != 0))
      {
        /* roda.cbl:108: MOVE */
        {
          cob_set_int ((f_17.data = b_16, &f_17), (*(int *) (b_1)));
        }
        /* roda.cbl:109: DISPLAY */
        {
          cob_display (0, 1, 3, &f_5, &c_3, (f_17.data = b_16, &f_17));
        }
        /* roda.cbl:110: GO TO */
        {
          goto l_5;
        }
      }
  }
  /* roda.cbl:113: IF */
  {
    if (((int)cob_cmp_s32_binary (b_22, 0) != 0))
      {
        /* roda.cbl:114: DISPLAY */
        {
          cob_display (0, 1, 5, &f_5, &c_4, (f_24.data = b_22, &f_24), &c_5, (f_25.data = b_22 + 4, &f_25));
        }
        /* roda.cbl:115: GO TO */
        {
          goto l_5;
        }
      }
  }
  /* roda.cbl:118: DISPLAY */
  {
    cob_display (0, 1, 2, &f_5, &c_6);
  }

  /* 000000-SAI */

  l_5:;
  /* roda.cbl:121: STOP */
  {
    cob_stop_run ((*(int *) (b_1)));
  }

  /* Program exit */

  /* Deallocate LOCAL storage */
  if (b_43) {
  	free (b_43);
  	b_43 = NULL;
  }
  if (b_22) {
  	free (b_22);
  	b_22 = NULL;
  }
  if (b_18) {
  	free (b_18);
  	b_18 = NULL;
  }
  if (b_16) {
  	free (b_16);
  	b_16 = NULL;
  }
  if (b_9) {
  	free (b_9);
  	b_9 = NULL;
  }

  /* Pop module stack */
  cob_current_module = cob_current_module->next;

  /* Program return */
  return (*(int *) (b_1));
}

/* End functions */

