/* Generated by            cobc 1.1.0 */
/* Generated from          roda.cbl */
/* Generated at            Nov 29 2016 04:08:24 BRST */
/* OpenCOBOL build date    Feb 07 2016 10:28:13 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -C roda.cbl */

/* Decimal structures */
static cob_decimal d0;
static cob_decimal d1;
static cob_decimal d2;
static cob_decimal d3;
static cob_decimal d4;


/* Define perform frame stack */

struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

unsigned char	*b_9 = NULL;	/* GRP-LS */
unsigned char	*b_16 = NULL;	/* GRP-ERRO */
unsigned char	*b_18 = NULL;	/* DATA-HORA */
unsigned char	*b_22 = NULL;	/* BOOK */
unsigned char	*b_43 = NULL;	/* PARM */
int		i1;
int		i2;

/* Local cob_field items */
cob_field	f0;

